# Generated by Django 3.0.3 on 2020-03-13 09:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_from', models.CharField(max_length=100)),
                ('user_to', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 3, 13, 9, 3, 17, 712359, tzinfo=utc))),
                ('msg', models.TextField()),
            ],
        ),
    ]
